# Generated by Django 5.2 on 2025-05-18 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Patient ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blurred_image', models.ImageField(upload_to='patient_images/blurred/')),
                ('grid_image', models.ImageField(upload_to='patient_images/grid/')),
                ('restored_image', models.ImageField(blank=True, null=True, upload_to='patient_images/restored/')),
                ('enhanced', models.BooleanField(default=False, help_text='Indicates if the restored image is enhanced')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_images', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ImageFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_histogram', models.BinaryField(help_text='Serialized color histogram data')),
                ('avg_hash', models.CharField(help_text='Average hash of the image', max_length=64)),
                ('phash', models.CharField(help_text='Perceptual hash of the image', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprint', to='patients.processedimage')),
            ],
        ),
        migrations.CreateModel(
            name='CroppedRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('x1', models.IntegerField()),
                ('y1', models.IntegerField()),
                ('x2', models.IntegerField()),
                ('y2', models.IntegerField()),
                ('cropped_image_data', models.BinaryField()),
                ('original_filename', models.CharField(max_length=255)),
                ('image_format', models.CharField(default='JPEG', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cropped_regions', to='patients.processedimage')),
            ],
        ),
    ]
