# Generated by Django 5.2 on 2025-05-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedimage',
            name='encrypted_entropy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processedimage',
            name='original_entropy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processedimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
