# Generated by Django 5.2 on 2025-05-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_processedimage_encrypted_entropy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='croppedregion',
            name='decryption_time_ms',
            field=models.FloatField(blank=True, help_text='Last decryption time in milliseconds', null=True),
        ),
        migrations.AddField(
            model_name='croppedregion',
            name='encryption_time_ms',
            field=models.FloatField(blank=True, help_text='Time taken to encrypt this region in milliseconds', null=True),
        ),
        migrations.AddField(
            model_name='processedimage',
            name='avg_decryption_time_ms',
            field=models.FloatField(blank=True, help_text='Average decryption time in milliseconds', null=True),
        ),
        migrations.AddField(
            model_name='processedimage',
            name='avg_encryption_time_ms',
            field=models.FloatField(blank=True, help_text='Average encryption time in milliseconds', null=True),
        ),
    ]
