# Generated by Django 5.2 on 2025-05-19 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_croppedregion_decryption_time_ms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='croppedregion',
            name='decryption_time_ms',
        ),
        migrations.RemoveField(
            model_name='croppedregion',
            name='encryption_time_ms',
        ),
        migrations.RemoveField(
            model_name='processedimage',
            name='avg_decryption_time_ms',
        ),
        migrations.RemoveField(
            model_name='processedimage',
            name='avg_encryption_time_ms',
        ),
    ]
