# Generated by Django 5.2 on 2025-05-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_remove_croppedregion_decryption_time_ms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='croppedregion',
            name='decryption_throughput',
            field=models.FloatField(blank=True, help_text='Decryption throughput in KB/s', null=True),
        ),
        migrations.AddField(
            model_name='croppedregion',
            name='decryption_time',
            field=models.FloatField(blank=True, help_text='Decryption time in milliseconds', null=True),
        ),
        migrations.AddField(
            model_name='croppedregion',
            name='encryption_throughput',
            field=models.FloatField(blank=True, help_text='Encryption throughput in KB/s', null=True),
        ),
        migrations.AddField(
            model_name='croppedregion',
            name='encryption_time',
            field=models.FloatField(blank=True, help_text='Encryption time in milliseconds', null=True),
        ),
        migrations.AddField(
            model_name='processedimage',
            name='decryption_throughput',
            field=models.FloatField(blank=True, help_text='Average decryption throughput in KB/s', null=True),
        ),
        migrations.AddField(
            model_name='processedimage',
            name='decryption_time',
            field=models.FloatField(blank=True, help_text='Average decryption time in milliseconds', null=True),
        ),
        migrations.AddField(
            model_name='processedimage',
            name='encryption_throughput',
            field=models.FloatField(blank=True, help_text='Average encryption throughput in KB/s', null=True),
        ),
        migrations.AddField(
            model_name='processedimage',
            name='encryption_time',
            field=models.FloatField(blank=True, help_text='Average encryption time in milliseconds', null=True),
        ),
    ]
