# Generated by Django 5.2 on 2025-05-19 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_croppedregion_decryption_throughput_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='croppedregion',
            name='decryption_throughput',
        ),
        migrations.RemoveField(
            model_name='croppedregion',
            name='decryption_time',
        ),
        migrations.RemoveField(
            model_name='croppedregion',
            name='encryption_throughput',
        ),
        migrations.RemoveField(
            model_name='croppedregion',
            name='encryption_time',
        ),
        migrations.RemoveField(
            model_name='processedimage',
            name='decryption_throughput',
        ),
        migrations.RemoveField(
            model_name='processedimage',
            name='decryption_time',
        ),
        migrations.RemoveField(
            model_name='processedimage',
            name='encryption_throughput',
        ),
        migrations.RemoveField(
            model_name='processedimage',
            name='encryption_time',
        ),
    ]
