# Generated by Django 5.2 on 2025-05-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_remove_croppedregion_decryption_throughput_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedimage',
            name='decryption_time',
            field=models.FloatField(blank=True, help_text='Decryption time in milliseconds', null=True),
        ),
        migrations.AddField(
            model_name='processedimage',
            name='encryption_time',
            field=models.FloatField(blank=True, help_text='Encryption time in milliseconds', null=True),
        ),
    ]
